### ISSUE TITLE
Review Tripal User's Guide Documentation for Docker Installation

### ISSUE THREAD

**Issue by spficklin** [erasche/docker-tripal#21]
Is there anything you would add to this page:
 
http://tripal.info/tutorials/v2.x/docker-setup

If so please feel free to edit.  The idea is to help folks who have zero experience with Docker at least get it up and running.

**Comment by abretaud** [comment]
I have just reviewed it, made a few corrections.
I hope it's ok for you!

**Comment by hexylena** [comment]
I'm sorry, I can't find my credentials for the wiki (and sincere apologies for never getting around to writing this, it just kept falling down further on my todo list, busy semester or three.) so just providing corrections here, maybe one of you two can add:

- curl command for fetching docker-compose should probably be a wget to do an actual download rather than just printing
- there is a `cd docker-tripal` after the docker-compose download, and no associated `mkdir`, probably just remove `cd docker-tripal`.
- `sudo docker exec -it dockertripal_web_1 /bin/bash` can be `sudo docker-compose exec -it web bash`, like they are taught earlier.

**Comment by spficklin** [comment]
No worries @erasche  :-) We're all busy.   You didn't have an account I discovered.  So, I added one for you.  You should receive an email for it.   I did work in your edits above, but now you can tweak if you like.

Thanks @abretaud for the edits!
